---
title: NY Public Radio Digital
timezone: America/New_York
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    author: NYPR Digital
    cover_image:
    layout: post
- scope:
    path: ''
    type: authors
  values:
    permalink: "/authors/:title/"
    image:
    job_title:
    twitter:
    layout: author
email:
description: Need to write something about us here
baseurl:
url:
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
