---
title: NY Public Radio Digital
timezone: America/New_York
collections:
  digital-team:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    author: digital-team
    cover_image: 
    layout: post
- scope:
    path: ''
    type: authors
  values:
    permalink: "/people/:title/"
    thumbnail: 
email: 
description: Need to write something about us here
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
